### ISSUE TITLE
SDK 2.x is not compatible. Should pin this to 1.5 (tested) or update the code for 2.x

### ISSUE THREAD

**Issue by markstur** [IBM/discovery-files#1]
Probably can just document the pip install w/ version specified.
To fix the code, there's at least some .get_result() call needed with the 2.x SDK migration.

**Comment by bruceadams** [comment]
Ugh. Yes. Need to do something here. I'd prefer to adjust the code to match the current release. Let me see if I can do that quickly.

Thanks for pointing this out!

**Comment by bruceadams** [comment]
OK. Updated the code to align with SDK 2.x and tested with SDK 2.1.0 (the current release).
